#!/usr/bin/env bash
## vim: ft=sh
## dftool: the script that makes the .magic happen
## TODO: more testing with strict mode
## TODO: reorganize with source->dest folders, pre/post unpack hooks 
## also maybe manage /etc ?
set -euo pipefail

# Get the real dotfiles directory
ABSOLUTE_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/$(basename "${BASH_SOURCE[0]}")"
DOTFILES_PATH=$(dirname "$ABSOLUTE_PATH")

# Hardcoded directories
DIR_BASE="$DOTFILES_PATH/home"
DIR_BAK="$DOTFILES_PATH/backups"
LOGFILE="$DOTFILES_PATH/dotfiles.log"

# Settings
VERBOSE=false
CLOBBER=false
QUIET=false

DESC="This script unpacks dotfiles stored in a git repo to your home directory."
USAGE="$DESC
$(basename "$0") [-vcqh] install/uninstall/list
\t-c\toverwrite existing files, regular files are backed up
\t-v\tverbose, show same information as the log
\t-q\tquiet, supress all output
\t-h\tshow this help text and exit"

# because readlink and realpath are unreliable
get_abs_path() {
  # $1 : relative filename
  echo "$(cd "$(dirname "$1")" && pwd)/$(basename "$1")"
}

function log(){
	# Log output to stdout and to a file.
	# Usage: log $text $force
	# text: The string the be logged
	# force: binary forcing the output to stdout regardless of the verbose 
	# argument
	# note: the quiet argument is still respected

	local TEXT=$1
    local FORCE=${2:-false}

	if ! $QUIET; then
        if $FORCE || $VERBOSE; then
            echo "$TEXT"
        fi
	fi
	echo "[$(date +%T)] $TEXT" >> "$LOGFILE"
}


function install_file(){
	# Link a file from the dotfiles directory to its destination
	# Usage: install_file $file $dest
	# file:	path to the file to be unpacked
	# dest: destination localtion
	# note: all paths must be absolute

	local file=$1
	local dest=$2

	# Assuming that symlinks are previous dotfiles installs
	if [[ -L "$dest" ]]; then
		log "Deleting $dest because it was a symbolic link."
		rm -f "$dest"

	elif [[ -e "$dest" ]]; then
		# Never overwrite regular files without asking
		# TODO: y/n/a prompt.
		if [[ "$CLOBBER" != true ]]; then
			log "Failed to install $file: destination exists." true
			return
		fi

		# Backup regular files in case they are being overwritten
		backup "$dest"
	fi

	log "Symlinking $file -> $dest"
	ln -s "$file" "$dest"
}

function install_dir(){
	# Unpack a directory to its destination
	# Usage: install_dir $dir $dest
	# dir: directory to be installed
	# dest: destination path
	# note: all paths must be absolute

	local dir=$1
	local dest=$2

	# Make sure a directory always exists before trying to symlink into it
	[[ -e "$dest" ]] || mkdir "$dest"

	# This is deprecated behaviour based on when the script used to symlink dir
	# TODO: Error or prompt the user for action when the destinatio directory
	# is a symlink
	if [[ -L "$dest" ]]; then
		log "Deleting $dest because it was a symbolic link."
		rm -f "$dest"
	fi

	# If the destination is a regular file then back it up
	# TODO: Might require user confirmation on this.
	[[ -d "$dest" ]] || backup "$dest"

	log "Unpacking directory $dir" true
	for item in $dir/*; do
		[[ $item == "$dir/*" ]] && break # emptry dir
		target="$dest/$(basename "$item")"
		if [[ -d $item ]]; then install_dir "$item" "$target"; else install_file "$item" "$target"; fi
	done
}

function backup(){
    # backup a file
    # Usage: backup $filepath
    # filepath: full path to file to be backed up

    local filepath=$1

    # figure out paths
    filename=$(basename "$filepath")
    bakdir="$DIR_BAK$(dirname $filepath)"
    bakfile="$bakdir/${filename#.}"

    # If the destination filename already exists, append a number to it
    if [[ -e "$bakfile" ]]; then
        i=1
        local newbakfile="$bakfile.$i"
        while [[ -e "$newbakfile" ]]; do
            let "i=i+1"
            newbakfile="$bakfile.$i"
        done
        bakfile=$newbakfile
    fi

    # Create destination backup directory if it doesnt exist
    [[ -e "$bakdir" ]] || mkdir -p "$bakdir"

    log "Backing up: $filepath -> $bakfile" true
    mv -f "$filepath" "$bakfile"
}

function get_managed_files() {
    # Get a list of all files managed inside a dotfiles folder
    # Usage: get_managed_files $source
    # source:  dotfiles folder.
    source_dir=${1:-}
    target_dir=${2:-}

    if [ -z "$source_dir" ]; then
        log "get_managed_files requires atleast 1 argument"
        exit 1
    fi

    for source in $source_dir/*; do
        # If we are in a subdirectory
        if [[  -n $target_dir ]]; then
            target="$target_dir/$(basename "$source")"
        else
            target="$HOME/.$(basename "$source")"
        fi

        # If source is a directory
        if [[ -d "$source" ]]; then
            get_managed_files "$source" "$target"
        else
            # Only symlinks are managed
            if  [[ -L $target ]]; then
                echo "$target"
            fi
        fi
    done
}

function get_managed_dirs() {
    source=$1

    dirs=($(find "$source"/* -type d))
    for dir in "${dirs[@]}"; do
        target="$HOME/.${dir#$source/}"
        echo "$target"
    done
}

# Commands
function install() {
    [[ -v "$1" ]] && BASE=$1 || BASE=$DIR_BASE

    log "Unpacking your dotfiles." true
    for item in $BASE/*; do
        item=$(get_abs_path "$item")
    	target="$HOME/.$(basename "$item")"
        if [[ -d "$item" ]]; then
            install_dir "$item" "$target"
        else
            install_file "$item" "$target"
        fi
    done
    log "Done unpacking." true
}

function uninstall() {
    [[ -n "$1" ]] && BASE=$1 || BASE=$DIR_BASE

    # Warn the user before you continue.
    read -rp "This operation is dangerous! type \"YES\" to continue? " choice
    [[ "$choice" != "YES" ]] && exit

    # First remove any symlinks
    files=($(get_managed_files "$BASE"))
    echo "Deleting symlinks."
    for file in "${files[@]}"; do
        log "Deleting Symlink: $file"
        rm "$file"
    done
    echo "Done."

    # Then delete empty directories
    dirs=($(get_managed_dirs "$BASE"))
    dirs=($(for i in "${dirs[@]}"; do echo "$i"; done | sort -r)) # Reverse sort the directories

    echo "Deleting empty directories"
    for dir in "${dirs[@]}"; do
        if [[ $(ls -A "$dir") ]]; then
            # Non-Empty directory
            log "$dir contains files, skipping!"
        else
            # Empty directory
            log "Deleting empty directory $dir"
            rm -r "$dir"
        fi
    done
    echo "Done."
}

function list_files() {
    [[ -n "$1" ]] && BASE=$1 || BASE=$DIR_BASE

    files=($(get_managed_files "$BASE"))
    for file in "${files[@]}"; do
        echo "$file"
    done
}


## Argument parsing
while [ $# -gt 0 ]; do
    ## Parse commands
    case "$1" in
        -h)
            echo -e "$USAGE"
            exit;;
        -v)
            VERBOSE=true;;
        -q)
            QUIET=true;;
        -c)
            CLOBBER=true;;
        install)
            shift
            DIR="${1:-}"
            install "$DIR"
            exit;;
        uninstall)
            shift
            DIR="${1:-}"
            uninstall "$DIR"
            exit;;
        list)
            shift
            DIR="${1:-}"
            list_files "$DIR"
            exit;;
        *)
            echo "Unknown argument: $1"
            echo -e "$USAGE"
            exit;;
    esac
    shift
done
