# vim: ft=sh
# Use the aur package xinit-xsession to run this from your login manager
# Its the best way to ensure everything runs the way i want without modifying /etc files

# how many times this script is run
# [ ! -d ~/xinitrun  ] && mkdir ~/xinitrun
# touch ~/xinitrun/"$(date +%s)"

# Run all system xinitrc shell scripts
xinitdir="/etc/X11/xinit/xinitrc.d"
if [ -d "$xinitdir" ]; then
    for script in $xinitdir/*; do
        echo "Loading xinit script $script"
        if [ -x "$script" -a ! -d "$script" ]; then
            . "$script"
        fi
    done
    unset xinitdir
    unset script
fi

# Session settings stored in ~/.xprofile
[ -r ~/.xprofile ] && source ~/.xprofile

exec awesome
