# vim: ft=sh
# Source ~/.profile
. $HOME/.profile

# Mute the annoying beep
xset -b

# Use native libs for steam
# https://wiki.archlinux.org/index.php/Steam#Using_native_runtime
export STEAM_RUNTIME=0

# Personal Keybinds
setxkbmap -option "terminate:ctrl_alt_bksp" & # Ctrl-Alt-Backspace kills xorg

# Load Xresources just in case
if [ -r ~/.Xresources ]; then
    xrdb -merge ~/.Xresources
fi

# Load xmodmap
command -v xmodmap && xmodmap ~/.xmodmaprc
